### ISSUE TITLE
README says to run a .exe that does not exsist

### ISSUE THREAD

**Issue by Polar-Onyx** [AoKishuba/ApsCalcUI#2]
I was just wondering what you meant to run the executable when there is no compiled .exe to speak of. I think it would be best to either include one or change the README to include instructions for how to compile one.

**Comment by AoKishuba** [comment]
Good catch! The discrepancy is there because I use the same README for the published .zip file (which contains an executable). It never occurred to me that there might not be one for someone running the program from the source code.

I don't know how to compile an executable from source code, unless that's what happens when using the Publish function in Visual Studio. I could change the wording in the README, though, to something like "If running from a downloaded .zip file, simply run the executable 'ApsCalcUI'".

**Comment by Polar-Onyx** [comment]
Where can I find the published zip? Sorry I'm kinda new to github. I heard about this from a youtube video and searching google only has this github and a few ancient reddit posts with a google sheet calcs that no longer work.

**Comment by AoKishuba** [comment]
All my public From the Depths documents are in my Google Drive folder [here](https://drive.google.com/drive/folders/1kZjE4-Og7MCuKI9Pa8zgO2eDLw0czb3o?usp=sharing).

I also have a Discord server where I post updates here: https://discord.gg/B7RrpZAA

I will add those links to the README.

Out of curiosity, which YouTube video did you see which mentioned my optimizer?

**Comment by Polar-Onyx** [comment]
A very small youtuber, he's quite good a FTD tho he mentions it in this video and I was curious https://www.youtube.com/watch?v=pn8QOSKUWE0

**Comment by Polar-Onyx** [comment]
regardless I think it would be good to link that google drive or at least put the zip in https://github.com/AoKishuba/ApsCalcUI/releases/

**Comment by AoKishuba** [comment]
I've updated every link I've ever posted on Reddit. If you see any which are out-of-date, please let me know.
I will look into posting the .zip as a release when I push a new update, which should be soon (just correcting a few typos, no functional changes).
