### ISSUE TITLE
Clip price savings not accounted for. giving belt feed autoloaders a inaccurate advantage

### ISSUE THREAD

**Issue by Polar-Onyx** [AoKishuba/ApsCalcUI#3]
Now that I've finally gotten to mess around with the calculator I've found it quite amazing.
The only issue I had was that belt feed autoloaders seemed to be giving much higher dps per cost due to being given the best-case scenario of 1 clip while 1m and other sizes were given worst-case scenario of having no clips
A few possible solutions:
1. account for 4 clips (and 5 inputs) for all the regular autoloaders (most people optimizing will want these numbers)
or
2. add a drop-down for 0-4 clips per autoloader (extra work but more flexible for oddly specific designs)

personally, I've never made aps cannons without 4 clips per loader except when they don't fit in a turret cap on the edge so I don't see much use in adding other options.
If I have some time later this week I might try poking around the code and implementing this myself.

**Comment by AoKishuba** [comment]
I've been considering this feature for a while, but the other day I witnessed the following comment from Draba:
"Depends, loaders are much more durable than clips (3x as much health, 20 armor instead of 8)
IMO loader only is generally plain better than clips, minor cost overhead but much more durable overall and don't have to bother with ejectors
But people still use 3-4 clip/loader for some reason so no reason to change it

...

Aside from the shell detonations, loaders can actually take some hits and you might still have a functional cannon
Anything touches clips and they are gone"

That was the final nail in the coffin for me.

Had I gotten around to implementing it, I would definitely have included options for 1-4 clips per loader, as well as ejector/no ejector. I recently participated in a semi-realism tournament with limited ROF and rather small spaces for guns, and found myself frequently using 3clip based on the results of [a calculator I made](https://docs.google.com/spreadsheets/d/1REKq8hJHu37TqV9FCmPFq2Sc79sD8B4MAI079Q35sqU/edit?usp=sharing). I've also seen many talk about using inline 2clip for railguns in order to avoid connectors.

**Comment by Polar-Onyx** [comment]
Overall I fail to see why someone would pay more for a worse turret just because it can fit in a slightly smaller space (recoil, coolers, and chargers take up a lot of space too).
with the extra money saved you could easily place HA in the front of the clips which offer far more protection for less price. When getting over-penetrated with clips it doesn't matter all you lose is a little ROF. Meanwhile using loaders only any over-penetration would mean that most of your loaders would be disconnected.

using loaders is a perfect excuse if you just need a turret or are lazy but for someone using a calculator like this to min/max their turret then 4 clips will always be optimal in all aspects except volume. And if you really care about the volume that much then you would be using missiles not APS.

**Comment by AoKishuba** [comment]
The main reasons I haven't added the feature are:
1. The UI is already cluttered, and if I ever get around to fully implementing railgun engine stats the way I'd like, it'll be even more so
2. Loader cost only affects comparisons across loader sizes; it doesn't affect the optimal shell for a given loader size

Looking at kinetic -- according to experienced players, the best shell type and one of the places where beltfeds shine -- I get the following results for 48AP (full printout at the bottom). Beltfed has the highest DPS/cost at 0.600; the next highest is 2m at 0.165.

The beltfed gets 233.87149 applied kinetic damage per second with a total cost of 1560.9668, of which 860 is from the loader, clip, and inputs.

The 2m gets 92.86711 applied kinetic damage per second with a total cost of 564.13385, of which 350 is from the loader and input.

Assuming 4clip, the 2m loader cost per input would be reduced to (300 + 200 * 4 ) / 5 + 50 = 270, giving a total cost per input of 484.13385 and bringing the 2m shell up to 0.192 DPS/cost. This is still totally swamped by the superior damage output from the beltfed shell.

1m (belt)
Gauge (mm): 18
Total length (mm): 359.8253
Length without casings: 54
Total modules: 20
GP casing: 16.990294
Solid body: 0
Sabot body: 1
Head: Heavy head
Recoil: 107.02505
Velocity (m/s): 1834.7859
Effective range (m): 1657.0872
Barrel length for inaccuracy (m): 0
Barrel length for propellant burn (m): 4.1022625
Raw KD: 97.32968
AP: 38.530502
Kinetic damage: 78.128365
Reload time: 0.22387627
Kinetic DPS: 233.87149
Loader volume: 4
Cooler volume: 3.210969
Charger volume: 0
Engine volume: 0
Fuel access volume: 0
Fuel storage volume: 0
Recoil volume: 3.983787
Ammo access volume: 0.14644335
Ammo storage volume: 0.29288667
Total volume: 11.634086
Kinetic DPS per volume: 78.86002
Cost per shell: 0.040768042
Loader cost: 860
Cooler cost: 160.54845
Charger cost: 0
Fuel burned: 0
Engine cost: 0
Fuel access cost: 0
Fuel storage cost: 0
Recoil cost: 318.70297
Ammo used: 219.66502
Ammo access cost: 1.4644334
Ammo storage cost: 0.58577335
Total cost: 1560.9668
Kinetic DPS per cost: 0.6002123

2m
Gauge (mm): 100
Total length (mm): 1999.0293
Length without casings: 300
Total modules: 20
GP casing: 16.990294
Solid body: 0
Sabot body: 1
Head: Heavy head
Recoil: 2344.2014
Velocity (m/s): 1834.786
Effective range (m): 9206.039
Barrel length for inaccuracy (m): 0
Barrel length for propellant burn (m): 10.534734
Raw KD: 2131.8408
AP: 38.53051
Kinetic damage: 1711.269
Reload time: 18.427073
Kinetic DPS: 92.86711
Loader volume: 3
Cooler volume: 0.9309657
Charger volume: 0
Engine volume: 0
Fuel access volume: 0
Fuel storage volume: 0
Recoil volume: 1.0601256
Ammo access volume: 0.054673396
Ammo storage volume: 0.109346785
Total volume: 5.1551113
Kinetic DPS per volume: 18.01457
Cost per shell: 0.83955884
Loader cost: 350
Cooler cost: 46.548286
Charger cost: 0
Fuel burned: 0
Engine cost: 0
Fuel access cost: 0
Fuel storage cost: 0
Recoil cost: 84.81004
Ammo used: 82.01009
Ammo access cost: 0.546734
Ammo storage cost: 0.21869357
Total cost: 564.13385
Kinetic DPS per cost: 0.16461892

**Comment by Polar-Onyx** [comment]
I never said 1m belt wasn't better, just that the calc gives them an inaccurate advantage.
All I was asking was to display the 0.192 DPS/cost instead of 0.164 to give a more accurate number of how they relate to each other.
for the example you gave the 1m belt has 3.8x the dps/cost of a normal 1m autoloader.
However, when tested in-game the results are negligible with a slight advantage to the belt closer to 1.1x cost/dps
![Screenshot_20220203_170036](https://user-images.githubusercontent.com/72043633/152444620-735a744b-d9d2-4925-a67a-726cdf77e34a.png)
top APS gun is a 1m autoloader and costs 1570
bottom APS gun is a 1m belt feed and costs 1510
even if you exclude the reload time of the belt feed you still get nowhere close to the advertised 3.8x dps/cost

Furthermore, this advantage goes away completely when using the calc's recommended setting of 50mm for the 1m autoloader
![Screenshot_20220203_172620](https://user-images.githubusercontent.com/72043633/152446413-6be60f84-5c77-45d1-b8a8-c4e88582fc92.png)
1780 vs 1510 (1.18x) cost difference for nearly double the dps
this gives the 1m autoloader a ~1.6x dps/cost advantage

I know these tests aren't precise but it at least shows how off the calculator numbers are. The bottom line is that belt feeds are very different in their usage and their calculations are different so maybe they shouldn't be directly compared with normal autoloaders but I think having similar metrics would help when deciding which one to choose

**Comment by AoKishuba** [comment]
The optimizer does not consider fixed costs, which will distort things somewhat by increasing the apparent cost difference. The optimizer also does not account for the fact that coolers, recoil absorbers, and rail chargers are all discrete components; thus, only an infinitely-large gun would approach the DPS/cost values given.

As far as clips go, I have the same two options I've had for every possible variable involved in designing an APS gun:
1. Spend the time adding another feature to a project on which I have spent a couple hundred hours at least
2. Make an arbitrary decision about hypothetical gun construction and hard-code the values

In this case, because the change wouldn't affect the shells themselves, I have chosen to go with the latter. If you can find a way to work clips-per-loader selection into the existing code, and make the dropdown fit nicely in the existing UI, then I will probably add it, but as it currently stands I have no plans to implement this feature myself.

**Comment by AoKishuba** [comment]
Feature added in version 2022-08-09
